- Dockerfile
- requirements.txt
- start-gateway-config.sh
Merges in requirements.txt move around.
> Python split

- config-python/advertisement.py
https://github.com/NebraLtd/hm-config/issues/40
> Fixes register_ad_error_callback TypeError

- Dockerfile
Bump bluez version to fix docker builds
**Why**
**How**
**References**
> bluez: bump version

- Dockerfile
- gatewayconfig/__main__.py
- gatewayconfig/bluetooth/advertisements/bluetooth_connection_advertisement.py
- gatewayconfig/bluetooth/characteristics/add_gateway_characteristic.py
- gatewayconfig/bluetooth/characteristics/assert_location_characteristic.py
- gatewayconfig/bluetooth/characteristics/diagnostics_characteristic.py
- gatewayconfig/bluetooth/characteristics/ethernet_online_characteristic.py
- gatewayconfig/bluetooth/characteristics/firmware_revision_characteristic.py
- gatewayconfig/bluetooth/characteristics/lights_characteristic.py
- gatewayconfig/bluetooth/characteristics/mac_address_characteristic.py
- gatewayconfig/bluetooth/characteristics/manufacturer_name_characteristic.py
- gatewayconfig/bluetooth/characteristics/onboarding_key_characteristic.py
- gatewayconfig/bluetooth/characteristics/public_key_characteristic.py
- gatewayconfig/bluetooth/characteristics/serial_number_characteristic.py
- gatewayconfig/bluetooth/characteristics/software_version_characteristic.py
- gatewayconfig/bluetooth/characteristics/wifi_configured_services_characteristic.py
- gatewayconfig/bluetooth/characteristics/wifi_connect_characteristic.py
- gatewayconfig/bluetooth/characteristics/wifi_remove_characteristic.py
- gatewayconfig/bluetooth/characteristics/wifi_services_characteristic.py
- gatewayconfig/bluetooth/characteristics/wifi_ssid_characteristic.py
- gatewayconfig/file_loader.py
- gatewayconfig/gatewayconfig_app.py
- gatewayconfig/logger.py
- gatewayconfig/processors/bluetooth_advertisement_processor.py
- gatewayconfig/processors/bluetooth_services_processor.py
- gatewayconfig/processors/diagnostics_processor.py
- gatewayconfig/processors/led_processor.py
- gatewayconfig/processors/wifi_processor.py
The old logger has been replaced with a more informative one.
Now we display:
* Time
* Error level
* The name of the file in which the event occurred
* Function name
* Path to file with line number
> New logger

- Dockerfile
- example/device_keys.txt
- gatewayconfig/__main__.py
- gatewayconfig/constants.py
- gatewayconfig/file_loader.py
- gatewayconfig/gatewayconfig_app.py
- gatewayconfig/processors/diagnostics_processor.py
- requirements.txt
- tests/gatewayconfig/test_file_loader.py
- tests/gatewayconfig/test_gatewayconfig_app.py
* Removes the need for `/var/data/public_keys`
* Fixes linting
* Bumps up hm-pyhelper
> Refactors how we retrieve the EC keys

- Dockerfile
**Why**
simplify dockerfiles and builds
**How**
move to install_packages form balena
**References**
https://github.com/NebraLtd/hm-diag/pull/189#discussion_r736186442
> feat: move to install_packages

- .github/pull_request_template.md
**Why**
We are setting up a new PR template 
**How**
Applied new PR template to PR file
**References**
[Issue 23](https://github.com/NebraLtd/product-management/issues/23)
> feat: New PR Template

- gatewayconfig/file_loader.py
- gatewayconfig/gatewayconfig_app.py
**Issue**
Related [#139](https://github.com/NebraLtd/hm-diag/issues/139)
**How**
Fix spam sentry error.
Add for sentry release version.
> Improve sentry. Fix error.

- start-gateway-config.sh
A follow-up for PR #165.
Just changed the sequence of the execution so that upnpc runs before gatewayconfig.
> Changed the sequence as gatewayconfig could prevent upnpc execution

- Dockerfile
- requirements.txt
**Issue**
- Link:
- Summary:
**How**
Add new hardware variant for Finestra and fix RAK and Sensecap profiles
**References**
**Checklist**
> feat: add new hardware variants

- gatewayconfig/bluetooth/characteristics/wifi_connect_characteristic.py
- requirements.txt
**Issue**
- Link: https://github.com/NebraLtd/hm-pyhelper/issues/130
- Summary: add pisces p100 support
**How**
bump hm-pyhelper to add pisces p100 support
**References**
https://github.com/NebraLtd/hm-pyhelper/issues/130
https://github.com/NebraLtd/hm-pyhelper/issues/131
https://github.com/NebraLtd/hm-pyhelper/issues/133
https://github.com/NebraLtd/helium-miner-software/pull/381
https://github.com/NebraLtd/hm-pktfwd/pull/87
https://github.com/NebraLtd/hm-block-tracker/pull/80
https://github.com/NebraLtd/hm-miner/pull/75
**Checklist**
> feat: add support for pisces p100

- requirements.txt
Bump RPI.gpio to latest version
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> feat: bump RPI.gpio

- requirements.txt
**Issue**
NebraLtd/helium-miner-software#465
**Checklist**
> Bumped hm-pyhelper to fix Cotx I2C addr issue

- Dockerfile
- start-gateway-config.sh
**Issue**
- Link:
- Summary: remove upnp
**How**
- we no longer need ports open due to move to light miner. So we can remove upnp
**References**
Closes: #167
**Checklist**
> feat: remove upnp

- Dockerfile
**Issue**
- Link:
- Summary: update to latest bullseye
**How**
update to latest bullseye base images to match with diag and pktfwd containers
**References**
**Checklist**
> feat: base image update to latest bullseye

- Dockerfile
- requirements.txt
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump pyhelper

- .github/workflows/compile-docker.yml
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> arch based buildcache

- gatewayconfig/processors/diagnostics_processor.py
- requirements.txt
bump hm-pyhelper
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> chore: bump hm-pyhelper

- .github/workflows/compile-docker.yml
- start-gateway-config.sh
We're removing host networking from all containers. Hence this had to be fixed.
**Checklist**
> Fixed: gateway-config doesn't work without host-networking

- gatewayconfig/__main__.py
> Fixed json load URL for non-host networking

- gatewayconfig/bluetooth/characteristics/add_gateway_characteristic.py
- gatewayconfig/helpers.py
- requirements.txt
**[Issue](https://nebraltd.atlassian.net/browse/NEBD-105)**
- Link: https://nebraltd.atlassian.net/browse/NEBD-105
- Summary:
**How**
**References**
**Checklist**
> fix: add create transaction with grpc #NEBD-105

- .github/workflows/security-audit.yml
- gatewayconfig/gatewayconfig_app.py
- gatewayconfig/gpio/neopixel_led.py
- pyproject.toml
- requirements.txt
- test-requirements.txt
- tests/gatewayconfig/gpio/test_neopixel_led.py
**Issue**
Add support for Neopixel LED strips present on Syncrobit units.
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add support for Syncrobit Neopixel LED strip

- requirements.txt
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump hm-pyhelper

- gatewayconfig/gatewayconfig_app.py
- gatewayconfig/gpio/button_common.py
- gatewayconfig/gpio/gpio_button.py
- gatewayconfig/gpio/gpio_led.py
- gatewayconfig/gpio/mraa_button.py
- gatewayconfig/processors/led_processor.py
- poetry.lock
- pyproject.toml
- tests/gatewayconfig/gpio/test_gpio_button.py
- tests/gatewayconfig/gpio/test_gpio_led.py
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Add support for sysfs GPIO

- Dockerfile
**Issue**
- Link:
- Summary:
**How**
**References**
**Checklist**
> Bump poetry
